// Generated by scripts/gen-types.mjs from the live schema. Do not edit by hand.
// Regenerate after any migration change:
//   bash scripts/local-supabase.sh && node scripts/gen-types.mjs

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admins: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agencies: {
        Row: {
          id: string;
          name: string;
          records_officer_email: string | null;
          records_officer_name: string | null;
          website: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          records_officer_email?: string | null;
          records_officer_name?: string | null;
          website?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          records_officer_email?: string | null;
          records_officer_name?: string | null;
          website?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      bodies: {
        Row: {
          id: string;
          name: string;
          slug: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
        };
        Relationships: [];
      };
      budget_categories: {
        Row: {
          id: string;
          fiscal_year: string;
          category: string;
          amount: number;
          source_url: string;
        };
        Insert: {
          id?: string;
          fiscal_year: string;
          category: string;
          amount: number;
          source_url: string;
        };
        Update: {
          id?: string;
          fiscal_year?: string;
          category?: string;
          amount?: number;
          source_url?: string;
        };
        Relationships: [];
      };
      corrections: {
        Row: {
          id: string;
          correction_date: string;
          page_path: string;
          what_changed: string;
          why: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          correction_date?: string;
          page_path: string;
          what_changed: string;
          why: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          correction_date?: string;
          page_path?: string;
          what_changed?: string;
          why?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      cpi: {
        Row: {
          year: number;
          index_value: number;
          source_url: string;
        };
        Insert: {
          year: number;
          index_value: number;
          source_url: string;
        };
        Update: {
          year?: number;
          index_value?: number;
          source_url?: string;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          owner_type: Database["public"]["Enums"]["document_owner_type"];
          owner_id: string | null;
          storage_path: string;
          file_name: string;
          file_size: number | null;
          page_count: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          owner_type: Database["public"]["Enums"]["document_owner_type"];
          owner_id?: string | null;
          storage_path: string;
          file_name: string;
          file_size?: number | null;
          page_count?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          owner_type?: Database["public"]["Enums"]["document_owner_type"];
          owner_id?: string | null;
          storage_path?: string;
          file_name?: string;
          file_size?: number | null;
          page_count?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      inquiries: {
        Row: {
          id: string;
          kind: Database["public"]["Enums"]["inquiry_kind"];
          name: string;
          email: string;
          audience: string | null;
          message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kind: Database["public"]["Enums"]["inquiry_kind"];
          name: string;
          email: string;
          audience?: string | null;
          message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database["public"]["Enums"]["inquiry_kind"];
          name?: string;
          email?: string;
          audience?: string | null;
          message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      listening_points: {
        Row: {
          id: string;
          session_id: string;
          kind: string;
          text: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          session_id: string;
          kind: string;
          text: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          session_id?: string;
          kind?: string;
          text?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "listening_points_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "listening_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      listening_sessions: {
        Row: {
          id: string;
          session_date: string;
          audience: Database["public"]["Enums"]["listening_audience"];
          attendee_count: number | null;
          summary: string | null;
          status: Database["public"]["Enums"]["publish_status"];
          published_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_date: string;
          audience: Database["public"]["Enums"]["listening_audience"];
          attendee_count?: number | null;
          summary?: string | null;
          status?: Database["public"]["Enums"]["publish_status"];
          published_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_date?: string;
          audience?: Database["public"]["Enums"]["listening_audience"];
          attendee_count?: number | null;
          summary?: string | null;
          status?: Database["public"]["Enums"]["publish_status"];
          published_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      people: {
        Row: {
          id: string;
          name: string;
          title: string | null;
          role: Database["public"]["Enums"]["person_role"];
          body_id: string | null;
          term_start: string | null;
          term_end: string | null;
          active: boolean;
          bio: string | null;
          photo_path: string | null;
          sort_order: number;
          created_at: string;
          email: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          title?: string | null;
          role: Database["public"]["Enums"]["person_role"];
          body_id?: string | null;
          term_start?: string | null;
          term_end?: string | null;
          active?: boolean;
          bio?: string | null;
          photo_path?: string | null;
          sort_order?: number;
          created_at?: string;
          email?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          title?: string | null;
          role?: Database["public"]["Enums"]["person_role"];
          body_id?: string | null;
          term_start?: string | null;
          term_end?: string | null;
          active?: boolean;
          bio?: string | null;
          photo_path?: string | null;
          sort_order?: number;
          created_at?: string;
          email?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "people_body_id_fkey";
            columns: ["body_id"];
            isOneToOne: false;
            referencedRelation: "bodies";
            referencedColumns: ["id"];
          },
        ];
      };
      records_requests: {
        Row: {
          id: string;
          agency_id: string;
          request_text: string;
          date_filed: string;
          status: Database["public"]["Enums"]["records_request_status"];
          date_responded: string | null;
          denial_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agency_id: string;
          request_text: string;
          date_filed?: string;
          status?: Database["public"]["Enums"]["records_request_status"];
          date_responded?: string | null;
          denial_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agency_id?: string;
          request_text?: string;
          date_filed?: string;
          status?: Database["public"]["Enums"]["records_request_status"];
          date_responded?: string | null;
          denial_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "records_requests_agency_id_fkey";
            columns: ["agency_id"];
            isOneToOne: false;
            referencedRelation: "agencies";
            referencedColumns: ["id"];
          },
        ];
      };
      report_sources: {
        Row: {
          id: string;
          report_id: string;
          label: string;
          url: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          report_id: string;
          label: string;
          url: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          report_id?: string;
          label?: string;
          url?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "report_sources_report_id_fkey";
            columns: ["report_id"];
            isOneToOne: false;
            referencedRelation: "reports";
            referencedColumns: ["id"];
          },
        ];
      };
      reports: {
        Row: {
          id: string;
          slug: string;
          title: string;
          type: Database["public"]["Enums"]["report_type"];
          report_date: string;
          summary: string | null;
          status: Database["public"]["Enums"]["publish_status"];
          preview_token: string;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          type: Database["public"]["Enums"]["report_type"];
          report_date: string;
          summary?: string | null;
          status?: Database["public"]["Enums"]["publish_status"];
          preview_token?: string;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          type?: Database["public"]["Enums"]["report_type"];
          report_date?: string;
          summary?: string | null;
          status?: Database["public"]["Enums"]["publish_status"];
          preview_token?: string;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      salary_schedule: {
        Row: {
          id: string;
          school_year: string;
          district: string;
          lane: string;
          step: number;
          salary: number;
          source_url: string;
        };
        Insert: {
          id?: string;
          school_year: string;
          district: string;
          lane: string;
          step: number;
          salary: number;
          source_url: string;
        };
        Update: {
          id?: string;
          school_year?: string;
          district?: string;
          lane?: string;
          step?: number;
          salary?: number;
          source_url?: string;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          key: string;
          value: string | null;
          is_public: boolean;
          updated_at: string;
        };
        Insert: {
          key: string;
          value?: string | null;
          is_public?: boolean;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: string | null;
          is_public?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscribers: {
        Row: {
          id: string;
          email: string;
          confirmed: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          confirmed?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          confirmed?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      vacancies: {
        Row: {
          id: string;
          as_of_date: string;
          position: string;
          building: string | null;
          posted_date: string | null;
          filled_date: string | null;
          source_url: string;
        };
        Insert: {
          id?: string;
          as_of_date: string;
          position: string;
          building?: string | null;
          posted_date?: string | null;
          filled_date?: string | null;
          source_url: string;
        };
        Update: {
          id?: string;
          as_of_date?: string;
          position?: string;
          building?: string | null;
          posted_date?: string | null;
          filled_date?: string | null;
          source_url?: string;
        };
        Relationships: [];
      };
      vote_members: {
        Row: {
          vote_id: string;
          person_id: string;
          vote: Database["public"]["Enums"]["vote_choice"];
        };
        Insert: {
          vote_id: string;
          person_id: string;
          vote: Database["public"]["Enums"]["vote_choice"];
        };
        Update: {
          vote_id?: string;
          person_id?: string;
          vote?: Database["public"]["Enums"]["vote_choice"];
        };
        Relationships: [
          {
            foreignKeyName: "vote_members_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vote_members_vote_id_fkey";
            columns: ["vote_id"];
            isOneToOne: false;
            referencedRelation: "votes";
            referencedColumns: ["id"];
          },
        ];
      };
      votes: {
        Row: {
          id: string;
          body_id: string;
          meeting_date: string;
          item_title: string;
          summary: string;
          category: Database["public"]["Enums"]["vote_category"];
          amount: number | null;
          agenda_url: string | null;
          minutes_url: string | null;
          yes_count: number;
          no_count: number;
          abstain_count: number;
          absent_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          body_id: string;
          meeting_date: string;
          item_title: string;
          summary: string;
          category?: Database["public"]["Enums"]["vote_category"];
          amount?: number | null;
          agenda_url?: string | null;
          minutes_url?: string | null;
          yes_count?: number;
          no_count?: number;
          abstain_count?: number;
          absent_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          body_id?: string;
          meeting_date?: string;
          item_title?: string;
          summary?: string;
          category?: Database["public"]["Enums"]["vote_category"];
          amount?: number | null;
          agenda_url?: string | null;
          minutes_url?: string | null;
          yes_count?: number;
          no_count?: number;
          abstain_count?: number;
          absent_count?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "votes_body_id_fkey";
            columns: ["body_id"];
            isOneToOne: false;
            referencedRelation: "bodies";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      latest_feed: {
        Row: {
          kind: string | null;
          title: string | null;
          subtitle: string | null;
          date: string | null;
          href: string | null;
        };
        Relationships: [];
      };
      member_vote_tallies: {
        Row: {
          person_id: string | null;
          name: string | null;
          title: string | null;
          body_name: string | null;
          body_slug: string | null;
          term_start: string | null;
          term_end: string | null;
          active: boolean | null;
          sort_order: number | null;
          votes_cast: number | null;
          yes_count: number | null;
          no_count: number | null;
          abstain_count: number | null;
          absent_count: number | null;
        };
        Relationships: [];
      };
      records_request_log: {
        Row: {
          id: string | null;
          date_filed: string | null;
          agency_name: string | null;
          request_text: string | null;
          status: Database["public"]["Enums"]["records_request_status"] | null;
          date_responded: string | null;
          denial_reason: string | null;
          response_business_days: number | null;
          open_business_days: number | null;
          document_count: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      business_days_between: {
        Args: { start_date: string; end_date: string };
        Returns: number;
      };
      is_admin: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: {
      document_owner_type: "records_request" | "report" | "listening" | "template";
      inquiry_kind: "contact" | "council" | "volunteer" | "briefing";
      listening_audience: "teachers" | "parents";
      person_role: "staff" | "board" | "advisory" | "body_member";
      publish_status: "draft" | "published";
      records_request_status: "filed" | "partial" | "fulfilled" | "denied";
      report_type: "pay_report" | "levy_explainer" | "contract_tracker";
      vote_category: "money" | "staffing" | "contracts" | "facilities" | "other";
      vote_choice: "yes" | "no" | "abstain" | "absent";
    };
  };
};
